### ISSUE TITLE
Buggy evaluation section

### ISSUE THREAD

**Issue by angelmtenor** [udacity/aind2-nlp-capstone#2]
The final section is buggy and uses the training data to make predictions. 

A version with a testing set and an accurate prediction section will show a better  evaluation of the Recurrent Neural Network. The following notebook uses this approach:
https://github.com/angelmtenor/data-science-keras/blob/master/NLP_machine_translation.ipynb

**Comment by cgearhart** [comment]
Added this as an additional step for students to complete in commit 3dd5cfc
